language: cpp

matrix:
  include:
    - os: windows
      env:
        - CMAKE_GENERATOR="MinGW Makefiles"
        - CMAKE_GENERATOR="Visual Studio 15 2017"
    - os: linux
      dist: xenial
      env:
        - CMAKE_GENERATOR="Unix Makefiles"

# todo: what effect has specifying compilers when building with cmake?
#compiler: gcc

before_script:
  - mkdir _build
  - cd _build
  - cmake -G \""CMAKE_GENERATOR"\" ..

script:
  - cmake --build .

after_success:
  - ./HelloGithub
