language: cpp

matrix:
  include:
    - os: windows
    - os: linux
      dist: xenial
      compiler: gcc
    - os: linux
      dist: xenial
      compiler: clang

before_script:
  - mkdir _build
  - cd _build
  - cmake -DCMAKE_BUILD_TYPE=Release ..

script:
  - cmake --build .

deploy:
  skip_cleanup: true
