language: cpp

matrix:
  include:
    - os: windows
      env: CMAKE_GENERATOR="MinGW Makefiles" CMAKE_BUILD_TYPE=Release
    - os: windows
      env: CMAKE_GENERATOR="MinGW Makefiles" CMAKE_BUILD_TYPE=Debug
    - os: windows
      env: CMAKE_GENERATOR="Visual Studio 15 2017" CMAKE_BUILD_TYPE=Release
    - os: windows
      env: CMAKE_GENERATOR="Visual Studio 15 2017" CMAKE_BUILD_TYPE=Debug
    - os: linux
      dist: xenial
      env: CMAKE_GENERATOR="Unix Makefiles" CMAKE_BUILD_TYPE=Release
    - os: linux
      dist: xenial
      env: CMAKE_GENERATOR="Unix Makefiles" CMAKE_BUILD_TYPE=Debug

# todo: what effect has specifying compilers when building with cmake?
#compiler: gcc

before_script:
  - mkdir _build
  - cd _build
  - cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -G "$CMAKE_GENERATOR" ..

script:
  - cmake --build .

after_success:
  - ./HelloGithub
