name: docs

on:
  push:
    branches:
      - master

jobs:
  docs:
    name: docs and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: build docs
        run: |
          cd doc
          doxygen

      - name: deploy docs
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc/_output/html
