name: mainCI

on: push

jobs:
  build:
    name: main configure and build
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
        mkdir _build
        cd _build
        cmake ..
    - name: build
      run: |
        cd _build
        cmake --build .
