name: os_matrix

on: push

jobs:
  build:
    name: main configure and build

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, windows-2016, windows-2019]

    steps:
    - uses: actions/checkout@v1
    - name: install deps
      run: sudo apt install libgl1-mesa-dev xorg-dev
      if: startsWith(matrix.os, 'ubuntu')
